---

- name: Send Discord Message
  hosts: all
  vars:
    discord_webhook: "{{ https://discord.com/api/webhooks/1283614885661511712/hJ8nqs84PwRE4r5MSupsWcGy9nhSH8S73aif-Ks4sD3-jVZWT9uN0NqW0zIQ_AxSburc }}"
    discord_name: 'Ansible Monitor'

  tasks:
    - include_role:
        name: hagher01.discord_webhook
      vars:
        discord_message: "This sends basic messages over to discord.  You can have multiple lines by using \n see?"
