
- hosts: all

  tasks:

    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage



    
    - hosts: localhost
      roles:
     - role: jtom38.ansible_discord_webhook
       discord_webhook_url: 'https://discord.com/api/webhooks/1283614885661511712/hJ8nqs84PwRE4r5MSupsWcGy9nhSH8S73aif-Ks4sD3-jVZWT9uN0NqW0zIQ_AxSburc/github'
       discord_message: 'Server output: {{  disk_usage }}'
      
